#ifndef __S2_APAD_LONG_TEXT_EDIT_H__
#define __S2_APAD_LONG_TEXT_EDIT_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_APAD_Long_Text_Edit_NEXTCHARINSELECTION_DIG_INPUT 0
#define __S2_APAD_Long_Text_Edit_PREVCHARINSELECTION_DIG_INPUT 1
#define __S2_APAD_Long_Text_Edit_NEXTCHARINTEXT_DIG_INPUT 2
#define __S2_APAD_Long_Text_Edit_PREVCHARINTEXT_DIG_INPUT 3
#define __S2_APAD_Long_Text_Edit_BACKSPACE_DIG_INPUT 4
#define __S2_APAD_Long_Text_Edit_DELETECHAR_DIG_INPUT 5
#define __S2_APAD_Long_Text_Edit_DONE_DIG_INPUT 6
#define __S2_APAD_Long_Text_Edit_CANCEL_DIG_INPUT 7
#define __S2_APAD_Long_Text_Edit_CLEAR_DIG_INPUT 8
#define __S2_APAD_Long_Text_Edit_INSERTSPACETORIGHT_DIG_INPUT 9
#define __S2_APAD_Long_Text_Edit_INSERTSPACETOLEFT_DIG_INPUT 10
#define __S2_APAD_Long_Text_Edit_DEBUG_DIG_INPUT 11


/*
* ANALOG_INPUT
*/
#define __S2_APAD_Long_Text_Edit_MAXNEWTEXTLENGTH_ANALOG_INPUT 0
#define __S2_APAD_Long_Text_Edit_MAXCHARACTERSINDISPLAY_ANALOG_INPUT 1

#define __S2_APAD_Long_Text_Edit_SELECTION$_STRING_INPUT 2
#define __S2_APAD_Long_Text_Edit_SELECTION$_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_APAD_Long_Text_Edit, __SELECTION$, __S2_APAD_Long_Text_Edit_SELECTION$_STRING_MAX_LEN );
#define __S2_APAD_Long_Text_Edit_TEXT$_STRING_INPUT 3
#define __S2_APAD_Long_Text_Edit_TEXT$_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_APAD_Long_Text_Edit, __TEXT$, __S2_APAD_Long_Text_Edit_TEXT$_STRING_MAX_LEN );



/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/
#define __S2_APAD_Long_Text_Edit_CURSORPOSITIONOUT_ANALOG_OUTPUT 0

#define __S2_APAD_Long_Text_Edit_TEXTEDIT$_STRING_OUTPUT 1
#define __S2_APAD_Long_Text_Edit_FINALTEXT$_STRING_OUTPUT 2


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_APAD_Long_Text_Edit_TEXTINTERMEDIATE$_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_APAD_Long_Text_Edit, __TEXTINTERMEDIATE$, __S2_APAD_Long_Text_Edit_TEXTINTERMEDIATE$_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_APAD_Long_Text_Edit )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   unsigned short __SELECTIONPOSITION;
   unsigned short __IMAXNEWTEXTLENGTH;
   unsigned short __CURSORPOSITION;
   DECLARE_STRING_STRUCT( S2_APAD_Long_Text_Edit, __TEXTINTERMEDIATE$ );
   DECLARE_STRING_STRUCT( S2_APAD_Long_Text_Edit, __SELECTION$ );
   DECLARE_STRING_STRUCT( S2_APAD_Long_Text_Edit, __TEXT$ );
};

START_NVRAM_VAR_STRUCT( S2_APAD_Long_Text_Edit )
{
};



#endif //__S2_APAD_LONG_TEXT_EDIT_H__

