#ifndef __S2_DMPS_TEXT_ROUTER_V1_0_H__
#define __S2_DMPS_TEXT_ROUTER_V1_0_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_DMPS_Text_Router_v1_0_UP_DIG_INPUT 0
#define __S2_DMPS_Text_Router_v1_0_DOWN_DIG_INPUT 1
#define __S2_DMPS_Text_Router_v1_0_ROUTEBTN_DIG_INPUT 2
#define __S2_DMPS_Text_Router_v1_0_VIEWBTN_DIG_INPUT 3
#define __S2_DMPS_Text_Router_v1_0_INFOBTN_DIG_INPUT 4
#define __S2_DMPS_Text_Router_v1_0_SYSPWRBTN_DIG_INPUT 5
#define __S2_DMPS_Text_Router_v1_0_SYSTEMPOWERSTATE_DIG_INPUT 6
#define __S2_DMPS_Text_Router_v1_0_SYSTEMREADY_DIG_INPUT 7
#define __S2_DMPS_Text_Router_v1_0_MODE_INSTALLER_NOT_ACTIVE_DIG_INPUT 8
#define __S2_DMPS_Text_Router_v1_0_FRONT_PANEL_BUTTON_PRESSED_DIG_INPUT 9

#define __S2_DMPS_Text_Router_v1_0_INPUT_DIGITALVIDEODETECTED_DIG_INPUT 10
#define __S2_DMPS_Text_Router_v1_0_INPUT_DIGITALVIDEODETECTED_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAVIDEODETECTED_DIG_INPUT 17
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAVIDEODETECTED_ARRAY_LENGTH 3
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCVIDEODETECTED_DIG_INPUT 20
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCVIDEODETECTED_ARRAY_LENGTH 1

/*
* ANALOG_INPUT
*/
#define __S2_DMPS_Text_Router_v1_0_DESTINATIONSELECTED_ANALOG_INPUT 0
#define __S2_DMPS_Text_Router_v1_0_VIEWMODEDESTINATION_ANALOG_INPUT 1
#define __S2_DMPS_Text_Router_v1_0_SELECTEDINOUT_ANALOG_INPUT 2



#define __S2_DMPS_Text_Router_v1_0_VIDEOINPUT_ANALOG_INPUT 3
#define __S2_DMPS_Text_Router_v1_0_VIDEOINPUT_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_AUDIOINPUT_ANALOG_INPUT 10
#define __S2_DMPS_Text_Router_v1_0_AUDIOINPUT_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDMIVERTICALRESOLUTION_ANALOG_INPUT 17
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDMIVERTICALRESOLUTION_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDMIHORIZONTALRESOLUTION_ANALOG_INPUT 24
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDMIHORIZONTALRESOLUTION_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDMIREFRESHRATE_ANALOG_INPUT 31
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDMIREFRESHRATE_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDCPENABLED_ANALOG_INPUT 38
#define __S2_DMPS_Text_Router_v1_0_INPUT_HDCPENABLED_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_OUTPUT_HDCPENABLED_ANALOG_INPUT 45
#define __S2_DMPS_Text_Router_v1_0_OUTPUT_HDCPENABLED_ARRAY_LENGTH 7
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAVERTICALRESOLUTION_ANALOG_INPUT 52
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAVERTICALRESOLUTION_ARRAY_LENGTH 3
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAHORIZONTALRESOLUTION_ANALOG_INPUT 55
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAHORIZONTALRESOLUTION_ARRAY_LENGTH 3
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAREFRESHRATE_ANALOG_INPUT 58
#define __S2_DMPS_Text_Router_v1_0_INPUT_VGAREFRESHRATE_ARRAY_LENGTH 3
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCVERTICALRESOLUTION_ANALOG_INPUT 61
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCVERTICALRESOLUTION_ARRAY_LENGTH 1
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCHORIZONTALRESOLUTION_ANALOG_INPUT 62
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCHORIZONTALRESOLUTION_ARRAY_LENGTH 1
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCREFRESHRATE_ANALOG_INPUT 63
#define __S2_DMPS_Text_Router_v1_0_INPUT_BNCREFRESHRATE_ARRAY_LENGTH 1
#define __S2_DMPS_Text_Router_v1_0_INPUT_VIDEOSOURCESELECT_ANALOG_INPUT 64
#define __S2_DMPS_Text_Router_v1_0_INPUT_VIDEOSOURCESELECT_ARRAY_LENGTH 3
#define __S2_DMPS_Text_Router_v1_0_SOURCENAMEIN$_STRING_INPUT 67
#define __S2_DMPS_Text_Router_v1_0_SOURCENAMEIN$_ARRAY_NUM_ELEMS 7
#define __S2_DMPS_Text_Router_v1_0_SOURCENAMEIN$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __SOURCENAMEIN$, __S2_DMPS_Text_Router_v1_0_SOURCENAMEIN$_ARRAY_NUM_ELEMS, __S2_DMPS_Text_Router_v1_0_SOURCENAMEIN$_ARRAY_NUM_CHARS );
#define __S2_DMPS_Text_Router_v1_0_DESTINATIONNAMEIN$_STRING_INPUT 74
#define __S2_DMPS_Text_Router_v1_0_DESTINATIONNAMEIN$_ARRAY_NUM_ELEMS 7
#define __S2_DMPS_Text_Router_v1_0_DESTINATIONNAMEIN$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __DESTINATIONNAMEIN$, __S2_DMPS_Text_Router_v1_0_DESTINATIONNAMEIN$_ARRAY_NUM_ELEMS, __S2_DMPS_Text_Router_v1_0_DESTINATIONNAMEIN$_ARRAY_NUM_CHARS );
#define __S2_DMPS_Text_Router_v1_0_MANF_STRING_STRING_INPUT 81
#define __S2_DMPS_Text_Router_v1_0_MANF_STRING_ARRAY_NUM_ELEMS 4
#define __S2_DMPS_Text_Router_v1_0_MANF_STRING_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __MANF_STRING, __S2_DMPS_Text_Router_v1_0_MANF_STRING_ARRAY_NUM_ELEMS, __S2_DMPS_Text_Router_v1_0_MANF_STRING_ARRAY_NUM_CHARS );
#define __S2_DMPS_Text_Router_v1_0_NAME_STRING_STRING_INPUT 85
#define __S2_DMPS_Text_Router_v1_0_NAME_STRING_ARRAY_NUM_ELEMS 4
#define __S2_DMPS_Text_Router_v1_0_NAME_STRING_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __NAME_STRING, __S2_DMPS_Text_Router_v1_0_NAME_STRING_ARRAY_NUM_ELEMS, __S2_DMPS_Text_Router_v1_0_NAME_STRING_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/
#define __S2_DMPS_Text_Router_v1_0_FRONTPANELMODE_ANALOG_OUTPUT 0

#define __S2_DMPS_Text_Router_v1_0_LINE2SCROLLARROW$_STRING_OUTPUT 1

#define __S2_DMPS_Text_Router_v1_0_SERIALOUT$_STRING_OUTPUT 2
#define __S2_DMPS_Text_Router_v1_0_SERIALOUT$_ARRAY_LENGTH 2

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_DMPS_Text_Router_v1_0_HDMIDMMODE_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_DMPS_Text_Router_v1_0, __HDMIDMMODE, __S2_DMPS_Text_Router_v1_0_HDMIDMMODE_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_DMPS_Text_Router_v1_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __INPUT_DIGITALVIDEODETECTED );
   DECLARE_IO_ARRAY( __INPUT_VGAVIDEODETECTED );
   DECLARE_IO_ARRAY( __INPUT_BNCVIDEODETECTED );
   DECLARE_IO_ARRAY( __VIDEOINPUT );
   DECLARE_IO_ARRAY( __AUDIOINPUT );
   DECLARE_IO_ARRAY( __INPUT_HDMIVERTICALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_HDMIHORIZONTALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_HDMIREFRESHRATE );
   DECLARE_IO_ARRAY( __INPUT_HDCPENABLED );
   DECLARE_IO_ARRAY( __OUTPUT_HDCPENABLED );
   DECLARE_IO_ARRAY( __INPUT_VGAVERTICALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_VGAHORIZONTALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_VGAREFRESHRATE );
   DECLARE_IO_ARRAY( __INPUT_BNCVERTICALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_BNCHORIZONTALRESOLUTION );
   DECLARE_IO_ARRAY( __INPUT_BNCREFRESHRATE );
   DECLARE_IO_ARRAY( __INPUT_VIDEOSOURCESELECT );
   DECLARE_IO_ARRAY( __SERIALOUT$ );
   unsigned short __LINE2DISPLAY;
   unsigned short __VIEWMODELINE2DISPLAY;
   unsigned short __VIEWMODE;
   unsigned short __VIEWMODESELECTION;
   unsigned short __INPUTVIDEODETECTED;
   DECLARE_STRING_STRUCT( S2_DMPS_Text_Router_v1_0, __HDMIDMMODE );
   DECLARE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __SOURCENAMEIN$ );
   DECLARE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __DESTINATIONNAMEIN$ );
   DECLARE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __MANF_STRING );
   DECLARE_STRING_ARRAY( S2_DMPS_Text_Router_v1_0, __NAME_STRING );
};

START_NVRAM_VAR_STRUCT( S2_DMPS_Text_Router_v1_0 )
{
};



#endif //__S2_DMPS_TEXT_ROUTER_V1_0_H__

