#ifndef __S2_STRINGSAVER_H__
#define __S2_STRINGSAVER_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_StringSaver_RECALLSETTINGS_DIG_INPUT 0


/*
* ANALOG_INPUT
*/



#define __S2_StringSaver_STRINGIN_STRING_INPUT 0
#define __S2_StringSaver_STRINGIN_ARRAY_NUM_ELEMS 50
#define __S2_StringSaver_STRINGIN_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_StringSaver, __STRINGIN, __S2_StringSaver_STRINGIN_ARRAY_NUM_ELEMS, __S2_StringSaver_STRINGIN_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_StringSaver_INITIALIZE_DIG_OUTPUT 0


/*
* ANALOG_OUTPUT
*/


#define __S2_StringSaver_STRINGOUT_STRING_OUTPUT 0
#define __S2_StringSaver_STRINGOUT_ARRAY_LENGTH 50

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_StringSaver_INITIALIZED_STRING_MAX_LEN 11
CREATE_STRING_STRUCT( S2_StringSaver, __INITIALIZED, __S2_StringSaver_INITIALIZED_STRING_MAX_LEN );
#define __S2_StringSaver_STRINGINSTORE_ARRAY_NUM_ELEMS 50
#define __S2_StringSaver_STRINGINSTORE_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_StringSaver, __STRINGINSTORE, __S2_StringSaver_STRINGINSTORE_ARRAY_NUM_ELEMS, __S2_StringSaver_STRINGINSTORE_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_StringSaver )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __STRINGOUT );
   DECLARE_STRING_ARRAY( S2_StringSaver, __STRINGIN );
};

START_NVRAM_VAR_STRUCT( S2_StringSaver )
{
   DECLARE_STRING_STRUCT( S2_StringSaver, __INITIALIZED );
   DECLARE_STRING_ARRAY( S2_StringSaver, __STRINGINSTORE );
};



#endif //__S2_STRINGSAVER_H__

